### PR TITLE
Add Hyperlinking

### PR DESCRIPTION
**Pull request by t-f-u-sys-co-jp**
Name field are now replace record page hyperlink.

### CODE REVIEW

**Comment by hrk623** [comment]
This is great! I didn't know that we can do it.
Do you think you can extend the modification so that it works for related records, too?
For example, it works for "opportunity.name", but not on "opportunity.account.name" nor "opportunity.owner.name".

**Comment by t-f-u-sys-co-jp** [comment]
Since It's get the record id of all related objects contained in the user specified field, we will need to make many changes.
利用者が入力したフィールド一覧からどのオブジェクトが関連しているのかリスト化し、それらすべてのレコードIdを取得するコードを挟まなくてはならないので、多くの変更が必要になるかと思います。
実利用の環境で関連オブジェクトについては要件に入っていないので、直近では対応する余裕がないです。すみません。

**Comment by hrk623** [comment]
Ok that is fine!
I will merge your changes first and try to figure out what I can do with the other name fields, too.
Thank you so much for your great contributions ;)

**Comment by ryoegu** [comment]
Cool. Thank you so much!

**Comment by hrk623** [comment]
Alright, the latest version has links on all Name fields(xxx.Name/xxx.Subject).

@t-f-u-sys-co-jp Do not forget to modify the sorting function as well, otherwise you will be sorting on the link urls.
see https://github.com/hrk623/record-hunter/commit/1078847a85700658080f32bde951491557fc4c66

**Pull request merged**
